name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: icepuma/rust-action@1.37.0
    - name: Format
      run: cargo fmt --check
    - name: Test
      run: cargo test --verbose --all --no-default-features
